### ISSUE TITLE
Consider more flexible ways of radius increment

### ISSUE THREAD

**Issue by imagejan** [Llamero/Local_Hough_Circle#1]
It would be useful to not limit the radius search steps to a linear increase. For large ranges, it might be useful to have an exponential increase function, such as 1, 2, 4, 8, 16, 32, ... or - not being limited to integers - for example 2, 3, 4.5, 6.75, ... i.e. `r *= 1.5` at each step.

Also, the plugin could be more tolerant with step sizes and automatically adjust the range if the increment is not an exact divisor of the range length.

What do you think?

**Comment by Llamero** [comment]
If I get a chance I can try and implement these as a branch.  The exponential could also be implemented as a work around by writing a macro that runs the transform for one radius, and then steps exponentially.  This approach would still be multi-threaded, so it should run pretty quick.

I also thought about the automatic adjustment of the radius limits to match an integer multiple of step sizes, but my worry was basically having the code become much like the Microsoft Word paperclip, technically helpful, but not really.  My worry is that by changing a parameter to what I think a user meant, will mean that there is a good chance the input will be changed automatically in a way the user did not anticipate or want.  That said, it would be easy to implement, but it does feel risky to guess what someone meant when they give an incorrect input.

For non-integer steps, a workaround would be to use a bicubic or bilinear expansion of the image.  One immediate problem I see with non-integer radii is that one of the outputs uses Bresenham's circle algorithm to quickly draw the outlines of circles found.  However, the algorithm requires integer radii as far as I can tell, so the circle outlined would not actually be the circle found.  It would take some testing to see, but I would also wager that if you ran a transform at radii of 20 vs 20,4, that the number of pixels different between those two radii would be negligible, since the result gets rounded to the nearest pixel.  Also, in most real data, the transform lacks subpixel precision as the input data itself lacks subpixel precision, since it has to be a binarized mask.

Just my two cents, but I'd love to hear your feedback on these points.
