### ISSUE TITLE
"Analysis complete" without running the analysis

### ISSUE THREAD

**Issue by czma** [Llamero/Local_Hough_Circle#7]
I have a macro that loops through images to run the plugin on each of them, but after a few rounds (usually the tenth), the "Analysis complete" message will appear, without the plugin actually running, and so the loop gets stuck, and I have to restart Fiji to continue the analysis. Any ideas why this happens and how I could fix it? Thanks!
The macro:
`
#@ File (label = "Input (DAPI) directory", style = "directory") inputDAPI
#@ File (label = "Input (GFP) directory", style = "directory") inputGFP
#@ File (label = "Output directory", style = "directory") output
#@ String (label = "File suffix", value = ".tif") suffix

processFolder();

function processFolder() {
	listDAPI = getFileList(inputDAPI);
	listGFP = getFileList(inputGFP);
	listOutput = getFileList(output);
	listDAPI = Array.sort(listDAPI);
	listGFP = Array.sort(listGFP);
	for (i = listOutput.length; i < listDAPI.length; i++) {
		if(endsWith(listDAPI[i], suffix)){
			print(i-listOutput.length);
        	processFile(listDAPI[i], listGFP[i]);
		}
    }
}

function processFile(fileDAPI, fileGFP) {
    print("Processing: " + inputDAPI + "/" + fileDAPI);
	open(inputDAPI + "/" + fileDAPI);
	run("Find Edges");
	setAutoThreshold("Otsu dark no-reset");
	setOption("BlackBackground", false);
	run("Convert to Mask");
        print("Processing: " + inputGFP + "/" + fileGFP);
	open(inputGFP + "/" + fileGFP);
	run("Find Edges");
	setAutoThreshold("Otsu dark no-reset");
	setOption("BlackBackground", false);
	run("Convert to Mask");
	run("Images to Stack", "name=Stack title=[] use");
	selectWindow("Stack");
	results = nResults;
	run("Hough Circle Transform","minRadius=10, maxRadius=100, inc=1, minCircles=1, maxCircles=100, threshold=0.5, resolution=656, ratio=1.0, bandwidth=100, local_radius=5,  reduce local_search show_mask results_table");
	while(results == nResults);
        wait(1000);
	selectWindow("Results");
        print("Saving to: " + output);
        saveAs("Results", output + "/" + replace(replace(fileDAPI, "_01_1_", "_"), "DAPI_001.tif", ".csv"));
	run("Close All");
	memory = IJ.freeMemory();
	memory = replace(memory, "MB.*", "");
	print(memory);
	selectWindow("Results");
	run("Close");
}`

**Comment by Llamero** [comment]
There was a memory leak issue that has been fixed.  I would first make sure you are using the most current version of the plugin.

**Comment by czma** [comment]
I'm pretty sure I'm using the most current version of the plugin, as I have UCB Vision Sciences among my update sites, and nothing changes when I run the Update... command in FIJI. I just tried re-running my code and it still stops at the 10 loop.

**Comment by Llamero** [comment]
Try the version attached below. It is a complete stab in the dark, but I added a return statement at the end of the plugin.  This should force FIJI to close the plugin between runs, although it should be doing that anyway.  That said, FIJI has shown odd behaviors before, so it is at least worth a try.  Let me know if it works.

[Hough_Circle_Transform-1.0.1-RELEASE.zip](https://github.com/Llamero/Local_Hough_Circle/files/2561093/Hough_Circle_Transform-1.0.1-RELEASE.zip)

**Comment by czma** [comment]
Thanks for try, but unfortunately, it didn't help.
Not sure if this is relevant or not, but:
1. When I decrease the max number of circles to 10 from 100, it still stops at the at the 10th loop.
2. When I kill my macro after the problem, close all image windows and the results table, then open a new image and try to run the plugin manually using the GUI, I get the "Analysis complete" message without the plugin running. I have to restart FIJI to get the plugin working again.

**Comment by Llamero** [comment]
Yeah that is odd, because with the return statement put in, that is the equivalent of forcing ImageJ to completely exit the plugin after each run.  Therefore, there shouldn't be anything carrying over between runs that would lock the macro on the plugin side, as each call should be independent from one another.

That said, I already had to fix a memory leak issue as ImageJ wasn't fully terminating each instance, and so I had to clear out all the major variables in the plugin.  In short, this sounds like this may be an issue on the ImageJ side of things, as the plugin is telling ImageJ to completely exit the plugin, but ImageJ is still doing something that is causing it to behave in a manner dependent on the number of times the plugin is called.

On a different note, I noticed that you are monitoring the RAM used in your code, do you see any memory leaks in your implementation?

**Comment by czma** [comment]
I see, thanks for your help, but if it's an ImageJ issue, I guess I'll just have to use a bash script or something to automate the restarting of ImageJ as part of the loop.

As for the RAM use, an example of what gets printed out to the log:
59
57
465
53
54
56
57
57
55
507

**Comment by Llamero** [comment]
Yeah, you definitely have the latest version as there is no memory leak.

If you are going to write a bash script, a better implementation would be to divide your data into blocks of 10 and run them in parallel instances of ImageJ, in order to do what I like to refer to as a "poor man's multithread."

The advantage of this strategy is that many processes in ImageJ are not multithreaded, so by running multiple instances of ImageJ iin parallel, you wind up effectively multithreading by parallelizing the processing across datasets, rather than by individual processing tasks.  

Since the Hough circle transform plugin is multithreaded, running multiple instances in parallel will slow this step down a bit as the kernel will be wildly flipping between multiple tasks, each of which are demanding the entire CPU, but in practice I've found this penalty not to be a major one, but this is also definitely architecture dependent.

The only thing you will need will be enough RAM, and to not have to use your computer (several multithreaded tasks trying to run simultanseously will greatly slow down your OS), but in general I've found this to be the fastest way to crunch through large datasets.

One other side note, ImageJ can close itself, and call new instances of itself from within the macro language.  I'd have to look the commands up again, but basically they are just the Java commands for starting a program and exiting the current JVM.  Finally a helpful use for the more insecure aspects of Java.

Good luck,
  Ben Smith
